// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPqYp8rCPM32Uo1waAYVlt9z_q2OXUWaA',
    appId: '1:173773260660:web:34d6351a725326d7e94e21',
    messagingSenderId: '173773260660',
    projectId: 'canteen-83bb8',
    authDomain: 'canteen-83bb8.firebaseapp.com',
    storageBucket: 'canteen-83bb8.appspot.com',
    measurementId: 'G-ZB06FBHZ3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUZyiPw-Vy6IIL69KOOcPNW2QEv363I84',
    appId: '1:173773260660:android:e8ccc3225182274ce94e21',
    messagingSenderId: '173773260660',
    projectId: 'canteen-83bb8',
    storageBucket: 'canteen-83bb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJWAGfAowBZ5u4XkZwgeOy_ciZz2fxj6I',
    appId: '1:173773260660:ios:cea0a555517f70bbe94e21',
    messagingSenderId: '173773260660',
    projectId: 'canteen-83bb8',
    storageBucket: 'canteen-83bb8.appspot.com',
    iosClientId: '173773260660-s95irs69s6m9gi1n1ol56ikv42rbcg93.apps.googleusercontent.com',
    iosBundleId: 'com.example.canteen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJWAGfAowBZ5u4XkZwgeOy_ciZz2fxj6I',
    appId: '1:173773260660:ios:cea0a555517f70bbe94e21',
    messagingSenderId: '173773260660',
    projectId: 'canteen-83bb8',
    storageBucket: 'canteen-83bb8.appspot.com',
    iosClientId: '173773260660-s95irs69s6m9gi1n1ol56ikv42rbcg93.apps.googleusercontent.com',
    iosBundleId: 'com.example.canteen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPqYp8rCPM32Uo1waAYVlt9z_q2OXUWaA',
    appId: '1:173773260660:web:04c35a7000d9c99fe94e21',
    messagingSenderId: '173773260660',
    projectId: 'canteen-83bb8',
    authDomain: 'canteen-83bb8.firebaseapp.com',
    storageBucket: 'canteen-83bb8.appspot.com',
    measurementId: 'G-3LQ9GE6CVW',
  );

}